const products = [
  {
    _id: "1",
    series: "first",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/images/item1.jpg",
    description:
      "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    series: "first",
    name: "iPhone 11 Pro 256GB Memory",
    image: "/images/item2.jpg",
    description:
      "Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life",
    brand: "Apple",
    category: "Electronics",
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    series: "first",
    name: "Cannon EOS 80D DSLR Camera",
    image: "/images/item3.jpg",
    description:
      "Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design",
    brand: "Cannon",
    category: "Electronics",
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    series: "first",
    name: "Sony Playstation 4 Pro White Version",
    image: "/images/item4.jpg",
    description:
      "The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music",
    brand: "Sony",
    category: "Electronics",
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    series: "first",
    name: "Logitech G-Series Gaming Mouse",
    image: "/images/item5.jpg",
    description:
      "Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience",
    brand: "Logitech",
    category: "Electronics",
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "6",
    series: "first",
    name: "Amazon Echo Dot 3rd Generation",
    image: "/images/item6.jpg",
    description:
      "Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space",
    brand: "Amazon",
    category: "Electronics",
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: "7",
    series: "second",
    name: "Sharp - High-Res 50W Main Unit and Speaker System",
    image: "/images/item7.jpg",
    description:
      "Enjoy crystal clear audio with this Sharp high-resolution component speaker system. Connect external devices via USB or the units optical input, and pair Bluetooth-enabled gadgets in seconds via the systems convenient NFC touchpoint.",
    brand: "Sharp",
    category: "Electronics",
    price: 159.99,
    countInStock: 2,
    rating: 4.5,
    numReviews: 18,
  },
  {
    _id: "8",
    series: "second",
    name: 'Dell - UltraSharp 24" IPS LED FHD Monitor (HDMI, USB)',
    image: "/images/item8.jpg",
    description:
      "Modify your computer setup with this 24-inch Dell Full HD UltraSharp monitor. The IPS panel has a 178-degree viewing angle that delivers crisp, detailed visuals from almost any direction",
    brand: "Dell",
    category: "Electronics",
    price: 245.99,
    countInStock: 17,
    rating: 4,
    numReviews: 2,
  },
  {
    _id: "9",
    series: "second",
    name: "Sharp - Stereo Turntable - Black",
    image: "/images/item9.jpg",
    description:
      "Enjoy great music with this Sharp stereo turntable. The built-in USB port lets you convert music from vinyl records to digital format, and the line out connects to speakers and other appliances for enhanced sound quality.",
    brand: "Sharp",
    category: "Electronics",
    price: 69.99,
    countInStock: 5,
    rating: 3,
    numReviews: 11,
  },
  {
    _id: "10",
    series: "second",
    name: "Sony - WH-1000XM4 Wireless Noise-Cancelling Over-the-Ear Headphones",
    image: "/images/item10.jpg",
    description:
      "Get up to 30 hours of battery life with quick charging capabilities, enjoy an enhanced Smart Listening feature set, and carry conversations hands-free with speak-to-chat.",
    brand: "Sony",
    category: "Electronics",
    price: 278,
    countInStock: 16,
    rating: 3.5,
    numReviews: 3,
  },
  {
    _id: "11",
    series: "second",
    name: "Sony - Alpha a7 III Mirrorless 4K Video Camera",
    image: "/images/item11.jpg",
    description:
      "Capture your subjects with beautiful results when you use the Sony a7 III full-frame mirrorless camera. A back-illuminated image sensor and evolved image processing system deliver high-quality images in a range of lighting conditions.",
    brand: "Sony",
    category: "Electronics",
    price: 1799,
    countInStock: 25,
    rating: 5,
    numReviews: 22,
  },
  {
    _id: "12",
    series: "second",
    name: "LG - 27.9 French Door Smart Wi-Fi Enabled Refrigerator",
    image: "/images/item12.jpg",
    description:
      "Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience",
    brand: "LG",
    category: "Electronics",
    price: 2699.99,
    countInStock: 3,
    rating: 2.5,
    numReviews: 19,
  },
  {
    _id: "13",
    series: "third",
    name: "LG - V60 ThinQ 5G Enabled - Classy Blue (AT&T)",
    image: "/images/item13.jpg",
    description:
      "Communicate effectively with this LG V60 ThinQ smartphone. The 6.8-inch OLED FullVision screen displays photos clearly and enables easy menu navigation, while the 10MP front-facing camera captures stunning selfies.",
    brand: "LG",
    category: "Electronics",
    price: 300.9,
    countInStock: 27,
    rating: 2.5,
    numReviews: 77,
  },
  {
    _id: "14",
    series: "third",
    name: "Samsung - T5 1TB External USB Type C Portable Solid State Drive",
    image: "/images/item14.jpg",
    description:
      "Store files securely on this 1TB Samsung portable SSD. It transfers data at speeds of up to 540MB/s for increased work productivity, and it connects to Android smart phones with a downloadable app, so you can backup pictures and music.",
    brand: "Samsung",
    category: "Electronics",
    price: 129.99,
    countInStock: 12,
    rating: 4,
    numReviews: 103,
  },
  {
    _id: "15",
    series: "third",
    name: 'LG - Gram 17" Laptop - Intel Core i7 - 16GB Memory - 1.024TB SSD',
    image: "/images/item15.jpg",
    description:
      "LG gram Laptop: Work on the go with this LG gram ultralightweight laptop. The 17-inch WQXGA IPS display delivers crisp, clear visuals, while an Intel Core i7 processor and 16GB of RAM provide unhindered performance.",
    brand: "LG",
    category: "Electronics",
    price: 1499.99,
    countInStock: 5,
    rating: 4.5,
    numReviews: 37,
  },
  {
    _id: "16",
    series: "third",
    name: 'Acer - Nitro 5 15.6" Laptop - Intel Core i5',
    image: "/images/item16.jpg",
    description:
      "LG gram Laptop: Travel lightly with this ultra-slim LG gram laptop. The Intel Core i5 processor and 8GB of RAM allow smooth multitasking for increased productivity, while the 256GB SSD loads programs quickly.",
    brand: "Acer",
    category: "Electronics",
    price: 699.99,
    countInStock: 15,
    rating: 3,
    numReviews: 73,
  },
  {
    _id: "17",
    series: "third",
    name: "Apple TV HD 32GB - Black",
    image: "/images/item17.jpg",
    description:
      "From TV shows to movies to games, it’s all available on Apple TV. Enjoy content from iTunes and apps like Apple TV+, Disney+, Netflix, Hulu and ESPN – or use the Siri Remote to find just what you want.",
    brand: "Apple",
    category: "Electronics",
    price: 149.99,
    countInStock: 34,
    rating: 1.5,
    numReviews: 6,
  },
  {
    _id: "18",
    series: "third",
    name:
      "G-Technology - G-Tech G-DRIVE 4TB External USB Type C Hard Drive - Silver",
    image: "/images/item18.jpg",
    description:
      "Provide reliable portable storage for your Mac or Windows PC with this G-Technology drive. It uses USB-C technology to transfer data at speeds as high as to 136MB/sec.",
    brand: "G-Technology",
    category: "Electronics",
    price: 179.95,
    countInStock: 72,
    rating: 5,
    numReviews: 59,
  },

  {
    _id: "19",
    series: "fourth",
    name: "Nextbase 622GW 4K Dash Cam",
    image: "/images/item19.jpg",
    description:
      "The best just got better with the new Nextbase 622GW 4K Dash Cam. With an abundance of new features and world’s firsts, the 622GW is the most accurate, powerful and highest image quality Dash Cam in the market today.",
    brand: "Nextbase",
    category: "Electronics",
    price: 299.99,
    countInStock: 87,
    rating: 4,
    numReviews: 72,
  },
  {
    _id: "20",
    series: "fourth",
    name: "BC 30 Wireless Back-Up Camera for Select Garmin GPS - Black",
    image: "/images/item20.jpg",
    description:
      "Back up safely using this Garmin BC 30 010-12242-10 wireless camera, which transmits footage to your GPS receiver from up to 45' away. A frame rate of up to 28 fps ensures smooth video.",
    brand: "Garmin",
    category: "Electronics",
    price: 154.99,
    countInStock: 9,
    rating: 3,
    numReviews: 125,
  },
  {
    _id: "21",
    series: "fourth",
    name: "Insignia - Front and Rear-Facing Camera Dash Cam - Black",
    image: "/images/item21.jpg",
    description:
      "Secure complete footage of vehicular incidents with this Insignia Full HD dual dash camera. The 1080p rear-facing and front cameras capture detailed events at different perspectives, and the G-force sensor supports automatic recording upon impact.",
    brand: "Insignia",
    category: "Electronics",
    price: 99.99,
    countInStock: 28,
    rating: 1.5,
    numReviews: 87,
  },
  {
    _id: "22",
    series: "fourth",
    name: "Ninja - Hot & Cold Brew 10-Cup Coffee Maker - Black/Stainless Steel",
    image: "/images/item22.jpg",
    description:
      "From TV shows to movies to games, it’s all available on Apple TV. Enjoy content from iTunes and apps like Apple TV+, Disney+, Netflix, Hulu and ESPN – or use the Siri Remote to find just what you want.",
    brand: "Ninja",
    category: "Electronics",
    price: 149.99,
    countInStock: 34,
    rating: 4.5,
    numReviews: 76,
  },
  {
    _id: "23",
    series: "fourth",
    name: "Fitbit - Sense Advanced Health & Fitness Smartwatch - Graphite.",
    image: "/images/item23.jpg",
    description:
      "Provide reliable portable storage for your Mac or Windows PC with this G-Technology drive. It uses USB-C technology to transfer data at speeds as high as to 136MB/sec.",
    brand: "G-Technology",
    category: "Electronics",
    price: 279.95,
    countInStock: 92,
    rating: 5,
    numReviews: 71,
  },
  {
    _id: "24",
    series: "fourth",
    name:
      "Citizen CZ Smart HR Heart Rate Smartwatch 46mm Blue Silicon Stainless Steel, Powered by Google Wear OS",
    image: "/images/item24.jpg",
    description:
      "The new CZ Smart smartwatch is designed for every moment. Inspired by the rich design of Citizen’s iconic sport technical timepieces, CZ Smart marries modern technologies with the style and quality you expect from Citizen.",
    brand: "Samsung",
    category: "Electronics",
    price: 395,
    countInStock: 35,
    rating: 4.5,
    numReviews: 10,
  },
];

export default products;
